CREATE CAST ( POLYGON AS LSEG )
    WITH FUNCTION __cast_polygon_to_lseg( POLYGON )
    AS IMPLICIT;

CREATE CAST ( POINT AS LSEG )
    WITH FUNCTION __cast_point_to_lseg( POINT )
    AS IMPLICIT;

CREATE CAST ( LINE AS LSEG )
    WITH FUNCTION __cast_line_to_lseg( LINE )
    AS IMPLICIT;

CREATE CAST ( PATH AS LSEG )
    WITH FUNCTION __cast_path_to_lseg( PATH )
    AS IMPLICIT;

CREATE CAST ( CIRCLE AS LSEG )
    WITH FUNCTION __cast_circle_to_lseg( CIRCLE )
    AS IMPLICIT;
